version: "3.4"

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    depends_on:
      - "beoo"

  beoo:
    container_name: "postgres-beoo"
    image: "postgres:13.4"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=beoo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beoo